@BASE_URL = http://localhost:3001/api

###Get all contacts
GET {{BASE_URL}}

###Create a new contact
POST {{BASE_URL}}
Content-Type: application/json

{
    "name": "John Doe",
    "number": "123456789"
}

###Delete a contact
DELETE {{BASE_URL}}/6717c7d2babfe4c12dbc6d20

  
