@BASE_URL = http://localhost:3001/api

###Get all contacts
GET {{BASE_URL}}

###Create a new contact
POST {{BASE_URL}}
Content-Type: application/json

{
    "name": "John Doe",
    "number": "123456789"
}

###Delete a contact
DELETE {{BASE_URL}}/672752509bcca2f3fbda2397

### Delete a contact with an invalid id to trigger malformatted id error
DELETE {{BASE_URL}}/invalid-id